import { PreferenceListData } from '../interfaces';
export type SupportedCurrency = 'USD' | 'EUR' | 'COP';

export const CURRENCY_FORMATS: Record<SupportedCurrency, string> = {
  USD: '$0,0.00',
  EUR: '€0,0.00',
  COP: '$0,0',
};

export const CURRENCIES: PreferenceListData[] = [
  { code: 'USD', name: 'Dólar estadounidense', icon: 'circle-flags:us' },
  { code: 'EUR', name: 'Euro', icon: 'circle-flags:eu' },
  { code: 'JPY', name: 'Yen japonés', icon: 'circle-flags:jp' },
  { code: 'GBP', name: 'Libra esterlina', icon: 'circle-flags:gb' },
  { code: 'AUD', name: 'Dólar australiano', icon: 'circle-flags:au' },
  { code: 'CAD', name: 'Dólar canadiense', icon: 'circle-flags:ca' },
  { code: 'CHF', name: 'Franco suizo', icon: 'circle-flags:ch' },
  { code: 'CNY', name: 'Yuan chino', icon: 'circle-flags:cn' },
  { code: 'SEK', name: 'Corona sueca', icon: 'circle-flags:se' },
  { code: 'NZD', name: 'Dólar neozelandés', icon: 'circle-flags:nz' },
  { code: 'MXN', name: 'Peso mexicano', icon: 'circle-flags:mx' },
  { code: 'SGD', name: 'Dólar de Singapur', icon: 'circle-flags:sg' },
  { code: 'HKD', name: 'Dólar de Hong Kong', icon: 'circle-flags:hk' },
  { code: 'NOK', name: 'Corona noruega', icon: 'circle-flags:no' },
  { code: 'KRW', name: 'Won surcoreano', icon: 'circle-flags:kr' },
  { code: 'TRY', name: 'Lira turca', icon: 'circle-flags:tr' },
  { code: 'INR', name: 'Rupia india', icon: 'circle-flags:in' },
  { code: 'BRL', name: 'Real brasileño', icon: 'circle-flags:br' },
  { code: 'RUB', name: 'Rublo ruso', icon: 'circle-flags:ru' },
  { code: 'ZAR', name: 'Rand sudafricano', icon: 'circle-flags:za' },
  { code: 'COP', name: 'Peso colombiano', icon: 'circle-flags:co' },
  { code: 'PLN', name: 'Zloty polaco', icon: 'circle-flags:pl' },
  { code: 'THB', name: 'Baht tailandés', icon: 'circle-flags:th' },
  { code: 'IDR', name: 'Rupia indonesia', icon: 'circle-flags:id' },
  { code: 'HUF', name: 'Florín húngaro', icon: 'circle-flags:hu' },
  { code: 'CZK', name: 'Corona checa', icon: 'circle-flags:cz' },
  { code: 'ILS', name: 'Nuevo shéquel israelí', icon: 'circle-flags:il' },
  { code: 'CLP', name: 'Peso chileno', icon: 'circle-flags:cl' },
  { code: 'PHP', name: 'Peso filipino', icon: 'circle-flags:ph' },
  { code: 'AED', name: 'Dirham de los Emiratos Árabes Unidos', icon: 'circle-flags:ae' },
  { code: 'MYR', name: 'Ringgit malayo', icon: 'circle-flags:my' },
  { code: 'RON', name: 'Leu rumano', icon: 'circle-flags:ro' },
  { code: 'ARS', name: 'Peso argentino', icon: 'circle-flags:ar' },
  { code: 'PKR', name: 'Rupia pakistaní', icon: 'circle-flags:pk' },
  { code: 'EGP', name: 'Libra egipcia', icon: 'circle-flags:eg' },
  { code: 'NGN', name: 'Naira nigeriana', icon: 'circle-flags:ng' },
  { code: 'BDT', name: 'Taka bangladesí', icon: 'circle-flags:bd' },
  { code: 'VND', name: 'Dong vietnamita', icon: 'circle-flags:vn' },
  { code: 'SAR', name: 'Rial saudí', icon: 'circle-flags:sa' },
  { code: 'QAR', name: 'Rial catarí', icon: 'circle-flags:qa' },
  { code: 'KWD', name: 'Dinar kuwaití', icon: 'circle-flags:kw' },
  { code: 'BHD', name: 'Dinar bareiní', icon: 'circle-flags:bh' },
  { code: 'OMR', name: 'Rial omaní', icon: 'circle-flags:om' },
];
